# Generated by Django 6.1.1 on 2026-10-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_playlist_remove_cancion_genero_cancion_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='artista',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
